[package]
name = "marla_markdown"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.143"
toml = "0.5.9"
pulldown-cmark = "0.9.2"
ammonia = "3.2.0"
maplit = "1.0.2"
anyhow = "1.0.61"